### ISSUE TITLE
How to pass options/attributes when doing the conversion?

### ISSUE THREAD

**Issue by patrickdung** [Djaler/vite-plugin-adoc#12]
In the readme, it mentioned
```  attributes - Any number of built-in or user-defined attributes;
    safe - Safe mode (unsafe, safe, server or secure).
```
How to specify the attributes passing to Asciidoctor?
I want to pass an attribute skip-front-matter: true when doing the conversion.
I am experimenting with Astro.

Thanks in advance.

**Comment by Djaler** [comment]
You can use `attributes` option, like
```
createAsciidocPlugin({
    attributes: {
        'skip-front-matter': true
    }
})
```

**Comment by patrickdung** [comment]
@Djaler
Yes, it is working.
Thanks for the help.
